### PR TITLE
#187: keepass reading

### PR DESCRIPTION
**Pull request by commjoen**
This PR is in honor of my friend Kees from Stormroxy! with the Kees-challenge!
When I showed this project to him, he said: that's kind of like my colleagues having a password manager with a very weak password?
And actually: we saw this already multiple times, so here we go: a fresh new challenge in the making ^^.
Thank you for submitting a pull request to the WrongSecrets app!

### CODE REVIEW

**Comment by commjoen** [comment]
@bendehaan can you please review the texts :) ?

**Comment by commjoen** [comment]
@nbaars i cannot figure out the challenge sort bug.. when i run the challenge from a container, i get misordered challenges and hte challenge breaks in heroku. when i run it from the IDE it does seem to work..

**Comment by commjoen** [comment]
Challenge is working at https://arcane-scrubland-42646.herokuapp.com/

**Comment by commjoen** [comment]
There still seems to be an issue at https://arcane-scrubland-42646.herokuapp.com/ , though it works with local docker containers...

**Comment by commjoen** [comment]
works at https://arcane-scrubland-42646.herokuapp.com/ now :)

**Review by bendehaan — APPROVED** [review]

**Pull request merged**
