### PR TITLE
Update challenge19_hint.adoc

### PR DESCRIPTION
**Pull request by alex-bender**
Update challenge19_hint.adoc with radare2 steps

https://github.com/commjoen/wrongsecrets/issues/148
https://twitter.com/commjoenie/status/1535922303422410754

### CODE REVIEW

**Comment by commjoen** [comment]
wh00t! Thank you for submitting your PR! Will check somewhere in this week!

**Review by commjoen — APPROVED** [review]
Thank you @alex-bender !!

**Comment by commjoen** [comment]
Just to make sure, can I mention you as `- [Alex Bender @alex-bender](https://github.com/alex-bender)` ? And what is your twitter handle so we can do a shoutout ?

**Comment by alex-bender** [comment]
So I don't see my response, which I did by email, what's strange.
You can mention, sure, handle is AlexBen58324598

**Comment by alex-bender** [comment]
Yes, you can. Here is the handle AlexBen58324598

**Pull request merged**
